version: "3.8"

volumes:
  pg_data:
  static:
  media:
  taski_pg_data:
  taski_static:

services:
  db:
    image: postgres:13
    container_name: db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: kleorii/kittygram_backend:latest
    container_name: backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/media
    command: gunicorn kittygram_backend.wsgi:application --bind 0:8000

  frontend:
    image: kleorii/kittygram_frontend:latest
    container_name: frontend
    volumes:
      - static:/static
    command: sh -c "cp -r /app/build/. /static/ && tail -f /dev/null"

  gateway:
    image: kleorii/kittygram_gateway:latest
    container_name: gateway
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static
      - media:/media
      - taski_static:/taski_static
      - /etc/letsencrypt:/etc/letsencrypt:ro

  taski_db:
    image: postgres:13
    env_file: .env
    volumes:
      - taski_pg_data:/var/lib/postgresql/data

  taski_backend:
    image: kleorii/taski_backend:latest
    env_file: .env
    depends_on:
      - taski_db
    expose:
      - "8000"

  taski_frontend:
    image: kleorii/taski_frontend:latest
    volumes:
      - taski_static:/taski_static