[tool.ruff]
line-length = 88
target-version = "py311"

select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings  
    "F",   # Pyflakes
    "I001", # isort
    "B",   # flake8-bugbear
]

exclude = [
    "tests/*",
    "migrations/*",
    "__pycache__/*",
    "*.pyi"
]
